# Generated by Django 4.2.7 on 2025-09-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("scrum_master", "Scrum Master"), ("employee", "Employee")],
                default="employee",
                max_length=20,
            ),
        ),
    ]
