# Generated by Django 4.2.7 on 2025-09-14 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_moved', 'Task Moved'), ('task_completed', 'Task Completed'), ('task_assigned', 'Task Assigned'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('comment_added', 'Comment Added'), ('file_uploaded', 'File Uploaded'), ('user_login', 'User Login'), ('user_logout', 'User Logout')], max_length=20)),
                ('entity_type', models.CharField(max_length=20)),
                ('entity_id', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='core_analyt_user_id_77c57e_idx'), models.Index(fields=['timestamp'], name='core_analyt_timesta_768eea_idx'), models.Index(fields=['entity_type', 'entity_id'], name='core_analyt_entity__383200_idx')],
            },
        ),
    ]
