# Generated by Django 5.2.6 on 2025-09-17 04:14

from django.db import migrations


def add_creators_as_members(apps, schema_editor):
    """Add project creators as admin members to their projects"""
    Project = apps.get_model('core', 'Project')
    ProjectMember = apps.get_model('core', 'ProjectMember')
    
    for project in Project.objects.all():
        # Check if creator is already a member
        if not ProjectMember.objects.filter(project=project, user=project.created_by).exists():
            ProjectMember.objects.create(
                project=project,
                user=project.created_by,
                role='admin'
            )
            print(f"Added {project.created_by.username} as admin member to project {project.name}")


def remove_creators_as_members(apps, schema_editor):
    """Remove project creators as members (reverse migration)"""
    Project = apps.get_model('core', 'Project')
    ProjectMember = apps.get_model('core', 'ProjectMember')
    
    for project in Project.objects.all():
        ProjectMember.objects.filter(project=project, user=project.created_by).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fix_email_uniqueness'),
    ]

    operations = [
        migrations.RunPython(add_creators_as_members, remove_creators_as_members),
    ]
